  - platform: mqtt
    name: "Aneliya"
    icon: mdi:camera
    command_topic: "cmnd/aneliya/power"
    state_topic: "stat/aneliya/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: broadlink
    host: 192.168.1.18
    mac: '34:EA:34:6F:E6:88'
  - platform: mqtt
    name: "Dining Main"
    icon: mdi:lamp
    command_topic: "cmnd/sonoffT1/power2"
    state_topic: "stat/sonoffT1/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Dining Lamp"
    icon: mdi:lamp
    command_topic: "cmnd/sonoffT1/power1"
    state_topic: "stat/sonoffT1/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Under Cabinet"
    icon: mdi:lamp
    command_topic: "cmnd/sonoff4/power"
    state_topic: "stat/sonoff4/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Garden_lights"
    icon: mdi:camera
    command_topic: "cmnd/garden/power"
    state_topic: "stat/garden/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "RealAmp"
    icon: mdi:camera
    command_topic: "cmnd/amp/power"
    state_topic: "stat/amp/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: broadlink
    host: 192.168.1.18
    mac: '34:EA:34:6F:E6:88'
    timeout: 15
    switches:
      projector:
        friendly_name: "Projector"
        command_on: 'JgBgAAABJpURFBE4ERQRFBE4ETkRFBISETkRExM3ETgRFBEUETgRORITETgSExEUERMRFBEUERMRORITETgRORE4ETgSOBE4EQAFJwABJksTAAxSAAEnShQADFEAASZLFAANBQAAAAAAAAAA'
        command_off: 'JgBQAAABKJMUERQ1FBEUERQ1FDYUERMRFDYUERM2FDUUERQRFDUUNhQREzYUNhM2FBEUNRQRFBEUNRQRFBETERQ2FBETNhQ2EwAFIwABKEoTAA0FAAAAAAAAAAA='
      screen:
        friendly_name: "Screen"
        command_on: 'eAgyAAYUBhQTCAYUEwcGFBMIBhQGFBMIBhQGFBMIEwgTBxMIEwgGFAYUBhQTCAYUBhQGwxMIAAAAAAAA'
        command_off: 'eAkyABMIFAcHEwcUBxMHFBQHBxQHwxQHBxQHExQHBxQUBwcUFAcHFAcUFAcHEwgTFAgUBxQHAAAAAAAA'
#    JgBQAAABJpURFBE4EhMRFBE4ETkRFBETETkRFBE4ETgSExEUETgSOBEUETgRORE4ERQROBEUERQROBEUERQRExI4ERQROBE5EQAFJQABJ0sRAA0FAAAAAAAAAAA=
